[project]
name = "videosharing"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
    "imagekitio>=5.2.0",
    "python-dotenv>=1.2.1",
]
